version: '3.8'

services:
  app:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./config/data:/app/config/data
    environment:
      - PYTHONUNBUFFERED=1
    command: python -m app.main